name: bempp
channels:
  - conda-forge
  - defaults
dependencies:
  - eigen>=3.3.7
  - fenics>=2019.1.0
  - gmsh>=4.4.1
  - ipython>=7.9.0
  - jupyter>=1.0.0
  - mpi4py>=3.0.2
  - mpich>=3.2.1
  - numba>=0.46.0
  - numpy>=1.16.5
  - pip>=19.3.1
  - plotly>=4.3.0
  - pocl>=1.4
  - pyopencl>=2019.1.2
  - pytest>=5.2.4
  - python>=3.7.3
  - scipy>=1.3.2
  - pip:
    - meshio>=4.0.1
    - matplotlib>=3.1.2
