version: 2.1

jobs:
  large-tests:
    docker:
      - image: bempp/cl-dev-env:latest
    steps:
      - checkout
      - run:
          command: python3 setup.py install
          name: Install Bempp
      - run:
          command: python3 -m pytest -n4 --durations=10 test/unit --has-dolfin 0 --has-dolfinx 0 --has-exafmm 1
          name: Run Bempp unit tests
      - run:
          command: python3 -m pytest -n2 --durations=10 test/validation --has-dolfin 0 --has-dolfinx 0 --has-exafmm 1
          name: Run Bempp validation tests
  run-notebooks:
    docker:
      - image: bempp/cl-dev-env:latest
    steps:
      - checkout
      - run:
          command: |
              apt-get -yq update
              apt-get -y install jupyter
          name: Install jupyter
      - run:
          command: python3 setup.py install
          name: Install Bempp
      - run:
      - run:
          command: python3 -m pytest -n2 --durations=10 notebooks/test_notebooks.py --has-dolfin 0 --has-dolfinx 0 --has-exafmm 1
          name: Run example notebooks
  run-notebooks-dolfin:
    docker:
      - image: bempp/cl-dev-env-with-dolfin:latest
    steps:
      - checkout
      - run:
          command: |
              apt-get -yq update
              apt-get -y install jupyter
          name: Install jupyter
      - run:
          command: python3 setup.py install
          name: Install Bempp
      - run:
      - run:
          command: python3 -m pytest -n2 notebooks/test_notebooks.py --has-dolfin 1 --has-dolfinx 0 --has-exafmm 1 --dolfin-books-only 1
          name: Run example notebooks
  run-notebooks-dolfinx:
    docker:
      - image: bempp/cl-dev-env-with-dolfinx:latest
    steps:
      - checkout
      - run:
          command: |
              apt-get -yq update
              apt-get -y install jupyter
          name: Install jupyter
      - run:
          command: python3 setup.py install
          name: Install Bempp
      - run:
      - run:
          command: python3 -m pytest -n2 notebooks/test_notebooks.py --has-dolfin 0 --has-dolfinx 1 --has-exafmm 1 --dolfin-books-only 1
          name: Run example notebooks
  run-benchmarks:
    docker:
      - image: bempp/cl-dev-env:latest
    steps:
      - checkout
      # TODO: run benchmarks and upload timings somewhere

workflows:
  main:
    jobs:
      - large-tests
      - run-notebooks
      - run-notebooks-dolfin
      - run-notebooks-dolfinx
      - run-benchmarks:
          filters:
            branches:
              only: master
  weekly:
    jobs:
      - large-tests
      - run-notebooks
      - run-notebooks-dolfin
      - run-notebooks-dolfinx
    triggers:
      - schedule:
          cron: "0 7 * * 1"
          filters:
            branches:
              only: master
